name = "PlantBiophysics"
uuid = "7ae8fcfa-76ad-4ec6-9ea7-5f8f5e2d6ec9"
authors = ["remi.vezy <VEZY@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
MutableNamedTuples = "af6c499f-54b4-48cc-bbd2-094bba7533c7"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
MutableNamedTuples = "0.1"
YAML = "0.4"
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
