name = "PlantBiophysics"
uuid = "7ae8fcfa-76ad-4ec6-9ea7-5f8f5e2d6ec9"
authors = ["remi.vezy <VEZY@users.noreply.github.com> and contributors"]
version = "0.7.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PlantMeteo = "4630fe09-e0fb-4da5-a846-781cb73437b6"
PlantSimEngine = "9a576370-710b-4269-adf9-4f603a9c6423"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
CSV = "0.8, 0.10"
DataFrames = "1"
LsqFit = "0.12, 0.13"
OrderedCollections = "1.3"
PlantMeteo = "0.1.2, 0.2"
PlantSimEngine = "0.1.9, 0.2"
RecipesBase = "1"
YAML = "0.4"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
