name = "PlantBiophysics"
uuid = "7ae8fcfa-76ad-4ec6-9ea7-5f8f5e2d6ec9"
authors = ["remi.vezy <VEZY@users.noreply.github.com> and contributors"]
version = "0.6.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
MultiScaleTreeGraph = "dd4a991b-8a45-4075-bede-262ee62d5583"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
AbstractTrees = "0.4"
CSV = "0.8, 0.10"
DataFrames = "1"
LsqFit = "0.12, 0.13"
MultiScaleTreeGraph = "0.4, 0.5, 0.6, 0.7, 0.8"
OrderedCollections = "1.3"
RecipesBase = "1"
Term = "1"
YAML = "0.4"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
